version: "2.1"

services:
  entities-db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: mydb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
      volumes:
        - dbdata:/var/lib/mysql
        - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
      restart: always
     ports:
      - "3306:3306"   
      
  entities-ms:
     depends_on:
       - entities-db
     build:
       context: .
     ports:
       - "8080:80"


volumes:
    dbdata:  