-- MySQL Script generated by MySQL Workbench
-- vie 19 oct 2018 22:03:16 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `mydb`.`Entity`
-- -----------------------------------------------------
USE `mydb`;


DROP TABLE IF EXISTS `Entity` ;

CREATE TABLE IF NOT EXISTS `Entity` (
  `idEntity` INT NOT NULL AUTO_INCREMENT,
  `TypeEntity` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Coordinates` VARCHAR(45) NULL,
  `Zone` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Score` ;

CREATE TABLE IF NOT EXISTS `Score` (
  `idScore` INT NOT NULL AUTO_INCREMENT,
  `ScoreEntity` DOUBLE NULL,
  `Commentary` VARCHAR(45) NULL,
  `Entity_idEntity` INT NOT NULL,
  PRIMARY KEY (`idScore`),
  INDEX `fk_Score_Entity_idx` (`Entity_idEntity` ASC),
  CONSTRAINT `fk_Score_Entity`
    FOREIGN KEY (`Entity_idEntity`)
    REFERENCES `mydb`.`Entity` (`idEntity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
